[IG]
ig = input/extensions-ig.xml
template = hl7.extensions.template#current
;hl7.extensions.template#1.0.0 = /Users/grahame/work/templates/hl7.extensions.template
;fhir2.base.template#current = /Users/grahame/work/templates/fhir2.base.template
;hl7.base.template#current = /Users/grahame/work/templates/hl7.base.template
;hl7.fhir.template#current= /Users/grahame/work/templates/hl7.fhir.template

